### PR TITLE
Markdown rewrite using hugo

### PR DESCRIPTION
**Pull request by tbabej**
This is a rough draft. Run using

```
hugo server -D
```

### CODE REVIEW

**Comment by djmitche** [comment]
I tried running hugo, and
```
funk ~/p/tw.org [md-rewrite*] $ ./hugo server -D
Start building sites … 
hugo v0.91.2-1798BD3F linux/amd64 BuildDate=2021-12-23T15:33:34Z VendorInfo=gohugoio
WARN 2022/01/09 17:47:42 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
Error: Error building site: failed to render pages: render of "home" failed: "/home/dustin/p/tw.org/themes/bootstrap/layouts/index.html:21:28": execute of template failed: template: index.html:21:28: executing "index.html" at <index ($.Site.Data.releases) 0>: error calling index: index of untyped nil
Built in 247 ms
```

Is there some secret sauce here to get the site data?  Perhaps a README update is in order?

How can I help this along?

**Comment by tbabej** [comment]
@djmitche Good catch! Turns out that I had to push one more file, which I considered unrelated, but was wrong. Can you try to re-run `hugo server -D` now?

**Comment by djmitche** [comment]
Much better!

**Comment by djmitche** [comment]
I made some README upadates here, but it appears I can't push to this branch :(

Also, I'm not sure what's done here and what's still to do ? It looks like it's got some stuff imported from timewarrior right now.  How can I help here?

**Comment by lauft** [comment]
Hello @djmitche, sorry for the late answer.

I have updated your access rights, see if you can push to this branch now.

The Timewarrior stuff is obviously copy paste from [ti.net](https://github.com/GothenburgBitFactory/ti.net), this has to be removed/adapted to the actual content of [taskwarrior.org](https://taskwarrior.org).

All in all I guess we have to go through each page and adapt the content so it is displayed correctly. As far as I have seen it, almost all top menu items are linked to the docs page (https://taskwarrior.org/docs/), so let's start here.
* Removing all clutter (`::: {.navbar-header} [Toggle navigation]{.sr-only} []{.icon-ba...` so we only see the bare content would be the first step.
* Fixing the links to the other pages is easy, simply remove the `.html`: `/docs/introduction.html` ▶️ `/docs/introduction`
* Do the same for every linked page...
I would first focus on getting the content readable. Getting the formatting right comes last.

**Comment by djmitche** [comment]
@lauft thoughts on how to handle the conflicts?

**Comment by tbabej** [comment]
The conflicts are present because this was branched off in August and some improvements were merged to the docs since then. I'll take care of it today.

**Comment by djmitche** [comment]
OK, I have converted everything in content/docs with reasonable formatting.  There's room for improvement but since this is blocking other work I think we should go for "pretty good with issues filed".

@tbabej do you want to fix the conflicts?

@lauft do you want to review?  What else will need to be done before we can turn this on?

**Comment by lauft** [comment]
Thanks for your work. I will review it as soon as possible. Please be patient.

**Comment by lauft** [comment]
@djmitche While reviewing the changes you made, I also started adapting the remaining pages to Markdown and Hugo.
This got a bit out of hand, but in the end I am now mostly through all of the pages and have pushed those changes to this branch. 

I agree with your idea to move the design documents to the Taskwarrior repository, however I moved the [How To Build Taskwarrior](https://taskwarrior.org/docs/build.html) back, as this page was also referenced from outside the 'news' section. Its content is definitely outdated (e.g. we do not work with patch submissions but pull requests), but that is something to fix later.

I would say there are only two things to do before we are ready to replace the old site:
- [ ] Merge all changes to the site which have happend since this branch branched off
- [ ] Rebase this branch onto `master` and adapt the update of `tools-data.json` to the way it is happening over on [ti.net](https://github.com/GothenburgBitFactory/ti.net).

After that I think the tasks left to do are
* 'Restore' the news section, i.e. display a short summary of each news item on the news list (currently only the title ist listed)
* Show recent news item(s) on front page (I would reduce this to the latest one...)
* Use Hugo shortcode to reference the lastest version on the web page, so we do not have to update all pages when a new release comes out
* Check documentations for outdated sections and update them

**Review by lauft — APPROVED** [review]

**Comment by lauft** [comment]
I have ironed out the big issues from the list above. For the rest I have created tickets
* News section 👉🏻 #423 
* Latest Taskwarrior version 👉🏻 #424
* FAQ 👉🏻 #425

**Pull request merged**
