### PR TITLE
Update with taskwarrior 2.5.3 release

### PR DESCRIPTION
**Pull request by Shadow53**
Updated the sidebar and download pages with links to version 2.5.3 of
Taskwarrior. Also added a news item that is basically text copied from
the tagged release on GitHub and edited news/index.html and feed.rss
with that entry.

I believe I have updated everything necessary, but a maintainer should probably
double check what I've done, and I will not be offended if any changes are suggested
or made. The one thing I have not updated is the tools page, as that is unrelated (I
think) to the release of Taskwarrior 2.5.3.

### CODE REVIEW

**Review by tbabej — APPROVED** [review]

**Comment by tbabej** [comment]
Thank you for taking the time!

**Comment by Shadow53** [comment]
No problem! Got tired of seeing next to no distros updating past 2.5.1, thought maybe updating the site would help.

**Comment by tbabej** [comment]
Changes are now live on the website.

**Comment by tbabej** [comment]
@Shadow53 Given the longer delay between 2.5.1 and 2.5.2, it might be worth considering contacting the maintainers directly, as the last release happened when TW was still hosted on the Atlassian stack.

**Comment by Shadow53** [comment]
Fair enough. I have seen Alpine and I think one other have updated to 2.5.3 and FreeBSD to 2.5.2. I just submitted an update to openSUSE for task- and timewarrior. Do you think it would make sense to make a tracking issue on the taskwarrior GitHub for getting the major distros updated? I'm fine with contacting the relevant maintainers and directing them there. I'm just not sure how to go about centralizing any discussion.

**Pull request merged**
